dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    update: true

before_install:
  - sudo apt-get install -y cmake mpi-default-dev mpi-default-bin libatlas-base-dev libboost-filesystem-dev

install:
  - git clone --branch fix-compiler-warnings https://github.com/kit-parco/lama.git
  - pushd lama && mkdir build && cd build && cmake ../scai && make -j4 && sudo make install && popd

script:
  - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install .. && make -j4 && sudo make install
  - mpirun -np 4 install/bin/GeographerTest