dist: xenial
language: cpp
compiler: gcc

matrix:
  include:
    - name: GCC5
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - name: GCC6
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    - name: GCC7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - name: GCC8
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - name: GCC9
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9" 

    - name: code_coverage
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      before_install:
        - pip install --user cpp-coveralls
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 -DCODE_COVERAGE=ON"   
      after_success:
        - coveralls --exclude lib --exclude tests --gcov-options '\-lp'         

addons:
  apt:
    update: true

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y cmake mpi-default-dev mpi-default-bin libatlas-base-dev libboost-filesystem-dev

install:
  - git clone --branch master https://github.com/hu-macsy/lama.git
  - pushd lama && mkdir build && cd build && cmake -DADDITIONAL_WARNING_FLAGS="" ../scai && make -j4 && sudo make install && popd

script:
  - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install .. && make -j4 && sudo make install && cd ..
  - mpirun -np 4 install/bin/GeographerTest